In [59]:
import pandas as pd 
import numpy as np

In [60]:
df=pd.read_csv("Training.csv")
print(df.head(-5))

                         Id  Runs  Boundaries  Six  Fifty  Hundred  Duck  \
0            1_Bipul Sharma     0           0    0      0        0     0   
1                1_DJ Hooda    16           1    1      0        0     0   
2               1_KM Jadhav    31           5    1      0        0     0   
3           1_Mandeep Singh    24           5    0      0        0     0   
4            1_Yuvraj Singh    62          10    3      1        0     0   
...                     ...   ...         ...  ...    ...      ...   ...   
15906       11415_RD Chahar     0           0    0      0        0     1   
15907       11415_JJ Bumrah     0           0    0      0        0     0   
15908       11415_SR Watson    84          12    4      1        0     0   
15909  11415_MJ McClenaghan     0           0    0      0        0     1   
15910      11415_SL Malinga     0           0    0      0        0     0   

       Batting_Points  Wickets  4W_Haul  5W_Haul  Maidens  Bowling_Points  \
0         

In [61]:
print(df.columns)

Index(['Id', 'Runs', 'Boundaries', 'Six', 'Fifty', 'Hundred', 'Duck',
       'Batting_Points', 'Wickets', '4W_Haul', '5W_Haul', 'Maidens',
       'Bowling_Points', 'Total Points'],
      dtype='object')


In [62]:
df['Id'].head(-5)

0              1_Bipul Sharma
1                  1_DJ Hooda
2                 1_KM Jadhav
3             1_Mandeep Singh
4              1_Yuvraj Singh
                 ...         
15906         11415_RD Chahar
15907         11415_JJ Bumrah
15908         11415_SR Watson
15909    11415_MJ McClenaghan
15910        11415_SL Malinga
Name: Id, Length: 15911, dtype: object

In [63]:
df["Idm"]=""
df["Name"]=""

In [64]:
for i in range(len(df)):
    df["Idm"][i],df["Name"][i]=df["Id"][i].split("_")[0],df["Id"][i].split("_")[1]

In [65]:
df["Name"][78].split("_")[0]

'AM Rahane'

In [66]:
df.columns

Index(['Id', 'Runs', 'Boundaries', 'Six', 'Fifty', 'Hundred', 'Duck',
       'Batting_Points', 'Wickets', '4W_Haul', '5W_Haul', 'Maidens',
       'Bowling_Points', 'Total Points', 'Idm', 'Name'],
      dtype='object')

In [67]:
df2=pd.read_csv("Matches IPL 2008-2019.csv")
df2.head()
print(df.Idm[0])

1


In [68]:
train=pd.DataFrame()
train['id']=df['Idm']
train['name']=df['Name']
#train['score']=df['Total Points']
train.head()

id           name
0  1   Bipul Sharma
1  1       DJ Hooda
2  1      KM Jadhav
3  1  Mandeep Singh
4  1   Yuvraj Singh

In [69]:
print(df2.columns)
train["team1"]=""
train["team2"]=""
train["venue"]=""

Index(['match_id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')


In [70]:
for i in range(len(df)):
    for j in range(len(df2)):
        if int(train['id'][i])==int(df2["match_id"][j]):
            print(i,j)
            train["venue"][i]=df2["venue"][j]
            train['team1'][i]=df2['team1'][j]
            train['team2'][i]=df2['team2'][j]
train['score']=df['Total Points']
train.head()

13916 662
13917 662
13918 662
13919 662
13920 662
13921 662
13922 662
13923 662
13924 662
13925 662
13926 662
13927 662
13928 662
13929 662
13930 662
13931 662
13932 662
13933 662
13934 663
13935 663
13936 663
13937 663
13938 663
13939 663
13940 663
13941 663
13942 663
13943 663
13944 663
13945 663
13946 663
13947 663
13948 663
13949 663
13950 663
13951 663
13952 663
13953 663
13954 663
13955 663
13956 664
13957 664
13958 664
13959 664
13960 664
13961 664
13962 664
13963 664
13964 664
13965 664
13966 664
13967 664
13968 664
13969 664
13970 664
13971 664
13972 664
13973 664
13974 664
13975 664
13976 664
13977 664
13978 665
13979 665
13980 665
13981 665
13982 665
13983 665
13984 665
13985 665
13986 665
13987 665
13988 665
13989 665
13990 665
13991 665
13992 665
13993 665
13994 665
13995 665
13996 665
13997 665
13998 665
13999 666
14000 666
14001 666
14002 666
14003 666
14004 666
14005 666
14006 666
14007 666
14008 666
14009 666
14010 666
14011 666
14012 666
14013 666
14014 666
14015 666


id           name                team1                        team2  \
0  1   Bipul Sharma  Sunrisers Hyderabad  Royal Challengers Bangalore   
1  1       DJ Hooda  Sunrisers Hyderabad  Royal Challengers Bangalore   
2  1      KM Jadhav  Sunrisers Hyderabad  Royal Challengers Bangalore   
3  1  Mandeep Singh  Sunrisers Hyderabad  Royal Challengers Bangalore   
4  1   Yuvraj Singh  Sunrisers Hyderabad  Royal Challengers Bangalore   

                                       venue  score  
0  Rajiv Gandhi International Stadium, Uppal     25  
1  Rajiv Gandhi International Stadium, Uppal     44  
2  Rajiv Gandhi International Stadium, Uppal     38  
3  Rajiv Gandhi International Stadium, Uppal     29  
4  Rajiv Gandhi International Stadium, Uppal     86

In [71]:
#train.to_csv("ipltrain"+".csv")

In [72]:
i20=pd.read_csv("Matches IPL 2020.csv")
i20.head()


match_id         city       date team1 team2  \
0   1216492    Abu Dhabi  9/19/2020    MI   CSK   
1   1216493  Dubai (DSC)  9/20/2020    DC  KXIP   
2   1216534  Dubai (DSC)  9/21/2020   SRH   RCB   
3   1216496      Sharjah  9/22/2020    RR   CSK   
4   1216508    Abu Dhabi  9/23/2020   KKR    MI   

                                 venue                  umpire1  \
0      Sheikh Zayed Stadium, Abu Dhabi           Chris Gaffaney   
1  Dubai International Cricket Stadium           Anil Chaudhary   
2  Dubai International Cricket Stadium            Anil Dandekar   
3              Sharjah Cricket Stadium  Chettithody Shamshuddin   
4      Sheikh Zayed Stadium, Abu Dhabi           Chris Gaffaney   

           umpire2                umpire3  
0  Virender Sharma          Sundaram Ravi  
1      Nitin Menon           Paul Reiffel  
2      Nitin Menon         Anil Chaudhary  
3  Vineet Kulkarni  KN Ananthapadmanabhan  
4    Sundaram Ravi        Virender Sharma

In [73]:
submit=pd.read_csv("sample_submission.csv")
print(i20.team1.unique())
i20.team1.nunique()

['MI' 'DC' 'SRH' 'RR' 'KKR' 'KXIP' 'CSK' 'RCB']


8

In [74]:
train=pd.read_csv("ipltrain.csv")
print(train.team1.unique())
train.team1.nunique()

['Sunrisers Hyderabad' 'Mumbai Indians' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Royal Challengers Bangalore'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kings XI Punjab'
 'Chennai Super Kings' 'Rajasthan Royals' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Rising Pune Supergiants'
 'Delhi Capitals']


15

In [75]:
for i in range(len(i20)):
    if i20['team1'][i]=="MI":
        i20['team1'][i]='Mumbai Indians'
    elif i20['team1'][i]=="DC":
        i20['team1'][i]='Delhi Daredevils'
    elif i20['team1'][i]=="SRH":
        i20['team1'][i]='Sunrisers Hyderabad'
    elif i20['team1'][i]=="RR":
        i20['team1'][i]='Rajasthan Royals'
    elif i20['team1'][i]=="KKR":
        i20['team1'][i]='Kolkata Knight Riders'
    elif i20['team1'][i]=="KXIP":
        i20['team1'][i]='Kings XI Punjab'
    elif i20['team1'][i]=="CSK":
        i20['team1'][i]='Chennai Super Kings'
    elif i20['team1'][i]=="RCB":
        i20['team1'][i]='Royal Challengers Bangalore'
print(i20.team1.unique())
i20.team1.nunique()

['Mumbai Indians' 'Delhi Daredevils' 'Sunrisers Hyderabad'
 'Rajasthan Royals' 'Kolkata Knight Riders' 'Kings XI Punjab'
 'Chennai Super Kings' 'Royal Challengers Bangalore']


8

In [82]:
for i in range(len(i20)):
    if i20['team2'][i]=="MI":
        i20['team2'][i]='Mumbai Indians'
    elif i20['team2'][i]=="DC":
        i20['team2'][i]='Delhi Daredevils'
    elif i20['team2'][i]=="SRH":
        i20['team2'][i]='Sunrisers Hyderabad'
    elif i20['team2'][i]=="RR":
        i20['team2'][i]='Rajasthan Royals'
    elif i20['team2'][i]=="KKR":
        i20['team2'][i]='Kolkata Knight Riders'
    elif i20['team2'][i]=="KXIP":
        i20['team2'][i]='Kings XI Punjab'
    elif i20['team2'][i]=="CSK":
        i20['team2'][i]='Chennai Super Kings'
    elif i20['team2'][i]=="RCB":
        i20['team2'][i]='Royal Challengers Bangalore'
print(i20.team2.unique())
i20.team2.nunique()

['Chennai Super Kings' 'Kings XI Punjab' 'Royal Challengers Bangalore'
 'Mumbai Indians' 'Delhi Daredevils' 'Sunrisers Hyderabad'
 'Kolkata Knight Riders' 'Rajasthan Royals']


8

In [83]:
test=pd.DataFrame()
submit.columns


Index(['Id', 'Total Points'], dtype='object')

In [111]:
test['id']=submit['Id']
test['idm']=""
test["name"]=""
test["venue"]=""
test["team1"]=""
test["team2"]=""

for i in range(len(submit)):
    d=test['id'][i].split("_")
    test["idm"][i]=d[0]
    test["name"][i]=d[1]
    for j in range(len(i20)):
        if int(test['idm'][i])==int(i20["match_id"][j]):
            print(i,j)
            test["venue"][i]=i20["venue"][j]
            test['team1'][i]=i20['team1'][j]
            test['team2'][i]=i20['team2'][j]


0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 0
16 0
17 0
18 0
19 0
20 0
21 0
22 1
23 1
24 1
25 1
26 1
27 1
28 1
29 1
30 1
31 1
32 1
33 1
34 1
35 1
36 1
37 1
38 1
39 1
40 1
41 1
42 1
43 1
44 1
45 38
46 38
47 38
48 38
49 38
50 38
51 38
52 38
53 38
54 38
55 38
56 38
57 38
58 38
59 38
60 38
61 38
62 38
63 38
64 38
65 38
66 55
67 55
68 55
69 55
70 55
71 55
72 55
73 55
74 55
75 55
76 55
77 55
78 55
79 55
80 55
81 55
82 55
83 55
84 3
85 3
86 3
87 3
88 3
89 3
90 3
91 3
92 3
93 3
94 3
95 3
96 3
97 3
98 3
99 3
100 3
101 3
102 3
103 3
104 41
105 41
106 41
107 41
108 41
109 41
110 41
111 41
112 41
113 41
114 41
115 41
116 41
117 41
118 41
119 41
120 41
121 41
122 41
123 41
124 41
125 41
126 41
127 42
128 42
129 42
130 42
131 42
132 42
133 42
134 42
135 42
136 42
137 42
138 42
139 42
140 42
141 42
142 42
143 42
144 42
145 42
146 42
147 42
148 42
149 47
150 47
151 47
152 47
153 47
154 47
155 47
156 47
157 47
158 47
159 47
160 47
161 47
162 47
163 47
164 47
165 47
166 47
167 47

In [112]:
test.groupby(["name","idm"]).sum()
test.head()

Unnamed: 0                    id      idm          name  \
0           0      1216492_AS Yadav  1216492      AS Yadav   
1           1     1216492_AT Rayudu  1216492     AT Rayudu   
2           2     1216492_DL Chahar  1216492     DL Chahar   
3           3  1216492_F du Plessis  1216492  F du Plessis   
4           4     1216492_HH Pandya  1216492     HH Pandya   

                             venue           team1                team2  
0  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
1  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
2  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
3  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
4  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings

In [113]:
test.to_csv("ipltest.csv")

In [101]:
train=pd.read_csv("ipltrain.csv")
train.head()
#train.drop(columns=["venue","team1","team2"],inplace=True)
#print(train.groupby(['name']).sum())
train["team2"].isnull().values

array([False, False, False, ..., False, False, False])

In [102]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le=LabelEncoder() 
#ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(sparse=False),["team1","team2"])], remainder='passthrough',) 
#train=np.array(ct.fit_transform(train))
train["name"]=le.fit_transform(train["name"])
train["venue"]=le.fit_transform(train["venue"])
train["team1"]=le.fit_transform(train["team1"])
train["team2"]=le.fit_transform(train["team2"])
train.head()

Unnamed: 0  id  name  team1  team2  venue  score
0           0   1    90     14     13     28     25
1           1   1   129     14     13     28     44
2           2   1   242     14     13     28     38
3           3   1   317     14     13     28     29
4           4   1   557     14     13     28     86

In [103]:
print(train.columns)
print(train.head())

Index(['Unnamed: 0', 'id', 'name', 'team1', 'team2', 'venue', 'score'], dtype='object')
   Unnamed: 0  id  name  team1  team2  venue  score
0           0   1    90     14     13     28     25
1           1   1   129     14     13     28     44
2           2   1   242     14     13     28     38
3           3   1   317     14     13     28     29
4           4   1   557     14     13     28     86


In [104]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
xtrain=train[["name","team1","team2","venue"]].copy()
trainy=train[["score"]].copy()
X_train, X_test, y_train, y_test = train_test_split(xtrain, trainy, test_size = 0.2, random_state = 0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [106]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100, random_state = 42)
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [110]:
from sklearn.metrics import mean_squared_error
preds = rf.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))
print(preds,y_test)

RMSE: 32.461425
[33.95519048 21.878      32.82933333 ... 33.7825     19.24802381
 18.96333333]        score
2445      50
8400      14
5570       5
13605     50
10087      0
...      ...
10914      2
2339      -2
12847     48
125       21
15074      0

[3184 rows x 1 columns]


In [115]:
test=pd.read_csv("ipltest.csv")
test.head()

Unnamed: 0  Unnamed: 0.1                    id      idm          name  \
0           0             0      1216492_AS Yadav  1216492      AS Yadav   
1           1             1     1216492_AT Rayudu  1216492     AT Rayudu   
2           2             2     1216492_DL Chahar  1216492     DL Chahar   
3           3             3  1216492_F du Plessis  1216492  F du Plessis   
4           4             4     1216492_HH Pandya  1216492     HH Pandya   

                             venue           team1                team2  
0  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
1  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
2  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
3  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings  
4  Sheikh Zayed Stadium, Abu Dhabi  Mumbai Indians  Chennai Super Kings

In [128]:
for i in range(len(test)):
    if type(test["name"][i]) is float:
        test["name"][i]="Nan"

In [129]:
print(test["id"][44])
print(test["name"][455])
print(test["name"][1194])

1216493_nan
Nan
Nan


In [132]:
test["name"]=le.fit_transform(test["name"])
test["venue"]=le.fit_transform(test["venue"])
test["team1"]=le.fit_transform(test["team1"])
test["team2"]=le.fit_transform(test["team2"])
testf=test[["name","venue","team1","team2"]].copy()
testf=sc.fit_transform(testf)
print(testf)

[[-1.57027882  1.19571271  0.2505009  -1.58163426]
 [-1.5483643   1.19571271  0.2505009  -1.58163426]
 [-1.08815934  1.19571271  0.2505009  -1.58163426]
 ...
 [ 1.21286544 -1.03895504 -1.05420543  0.15945262]
 [ 1.23477996 -1.03895504 -1.05420543  0.15945262]
 [ 1.49775422 -1.03895504 -1.05420543  0.15945262]]


In [134]:
predfinal = rf.predict(testf)

In [135]:
print(predfinal)

[66.12       28.60666667 62.1        ... 26.31       20.28
 26.05183333]


In [140]:
sub=pd.read_csv("sample_submission.csv")
subf=pd.DataFrame()
subf["Id"]=sub["Id"]

In [144]:
subf["Total Points"]=predfinal
subf.head()

Id  Total Points
0      1216492_AS Yadav     66.120000
1     1216492_AT Rayudu     28.606667
2     1216492_DL Chahar     62.100000
3  1216492_F du Plessis     27.970000
4     1216492_HH Pandya     35.911667

In [147]:
subf.to_csv("submit.csv",index=False)

In [148]:
subf.reset_index()
subf.head()

Id  Total Points
0      1216492_AS Yadav     66.120000
1     1216492_AT Rayudu     28.606667
2     1216492_DL Chahar     62.100000
3  1216492_F du Plessis     27.970000
4     1216492_HH Pandya     35.911667